# Site settings
title: "Data Day Health"
description: "Description of the website"
podcast-description: "This is your podcast's summary."
url:  "https://datadayhealth.github.io/" # Actual base url of the website
baseurl: "/"                    # url of the jekyll blog. e.g. if you set url to "mysite.com" and baseurl to "blog", the jekyll website will work on "mysite.com/blog"
author:
  name: "Florence Townend"
  email: "f.j.townend@live.com"
permalink: pretty
permalink: /:title
keywords: [podcast]
theme: jekyll-podcaster

#Plugins
plugins: [jekyll-paginate, jekyll-seo-tag, jekyll-sitemap]

#exclude: [_podcast.rss] #Ignore this, it will be used in case I decide to add rss feed

#Pagination
paginate: 5
paginate_path: "/page-:num/"

#Sass
sass:
  style: compressed
  sourcemap: never

#SEO
facebook:
  app_id: 
logo: /assets/img/Podcast_Cover.jpg
social:
  name: Data Day Health
  links:
    - https://github.com/datadayhealth
    - https://instagram.com/datadayhealth
    - https://youtube.com/@Turing-Roche
lang: en

#Podcast Metadata. Used by the RSS Feed, which currently isn't in use. So you can avoid this
podcast_title: Data Day Health
podcast_author: Florence Townend and Davy Tennison
podcast_email: 
podcast_subtitle: 
podcast_summary: 
podcast_description: 
podcast_explicit: 
podcast_type: 
podcast_lang: 
podcast_launch: 
podcast_copyright: 
podcast_feed: 
podcast_artwork: 